<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="colors.xacro"/>
    <xacro:include filename="demo_robot_params.xacro"/>
    <xacro:include filename="demo_robot_inertial_macros.xacro"/>
    <xacro:include filename="demo_robot_gazebo.xacro"/>

    <link name="world"></link>

    <!-- Common types: revolute,continuous, prismatic, fixed -->
    <!-- BASE JOINT -->
    <joint name="base_joint" type="fixed">
        <origin xyz="1.5 1.0 0.0" rpy="0.0 0.0 0.0"/>
        <parent link="world"/>
        <child link="base_link"/>
    </joint>




    <!-- BASE LINK -->
    <link name="base_link">
        <visual>
            <origin xyz="0.0 0.0 0.05" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="2.5 1.5 0.1"/>
            </geometry>
            <material name="black"/>
        </visual> 

        <collision>
            <origin xyz="0.0 0.0 0.05" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="2.5 1.5 0.1"/>
            </geometry>
        </collision>

        <inertial>
            <origin xyz="0 0 0.05" rpy="0 0 0"/>
            <mass value="12" />
            <inertia ixx="2.26" ixy="0.0" ixz="0.0" iyy="6.26" iyz="0.0" izz="8.5" />
        </inertial> 
    </link>

    <!-- SLIDER JOINT THAT WILL TRANSLATE ONLY -->
    <joint name="slider_joint" type="prismatic">
        <!-- IT SPANWS IN THE CENTER OF THE BASELINK, SO WE WILL PUT THE ORIGIN BACK TO ITS EDGE -->
        <origin xyz="-1.0 0 0.1" rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="slider_link"/>
        <!-- IN WHAT AXIS DOES IT TRANSLATE? -->
        <axis xyz="1 0 0"/>
        <limit lower="0" upper="2" velocity="100" effort="100"/> 
        <dynamics damping="10.0" friction="10.0"/>
    </joint>


    <!-- SLIDER LINK OBJECT THAT WILL BE TRANSLATING -->
    <link name="slider_link">
        <visual>
            <origin xyz="0 0 0.075" rpy="0 0 0"/>
            <geometry>
                <box size="0.5 0.25 0.15" />
            </geometry>
            <material name="white" />
        </visual>
        <collision>
            <origin xyz="0 0 0.075" rpy="0 0 0"/>
            <geometry>
                <box size="0.5 0.25 0.15" />
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.5" x="0.5" y="0.25" z="0.15">
            <origin xyz="0 0 0.075" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <!-- ARM JOINT THAT WILL BE ROTATING -->
    <joint name="arm_joint" type="revolute">
        <origin xyz="0.25 0 0.15" rpy="0 0 0"/>
        <parent link="slider_link"/>
        <child link="arm_link"/>
        <!-- WHAT AXIS IS IT ROTATING IN AND IS IT CW OR CCW? -->
        <axis xyz="0 -1 0"/>
        <limit lower="0" upper="${pi/2}" velocity="100" effort="100"/> 
        <dynamics damping="10.0" friction="10.0"/>
    </joint>

    <!-- THE ARM THAT WILL BE ROTATING -->
    <link name="arm_link">
        <visual>
            <!-- ROTATING IT ON Y AXIS SO IT START OUT AS HORIZONTAL -->
            <origin xyz="${arm_length/2} 0 0" rpy="0 ${pi/2} 0"/>
            <geometry>                
                <cylinder length="${arm_length}" radius="${arm_radius}" />
            </geometry>
            <material name="orange" />
        </visual>
        <collision>
            <origin xyz="${arm_length/2} 0 0" rpy="0 ${pi/2} 0"/>
            <geometry>
                <cylinder length="${arm_length}" radius="${arm_radius}" />
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="1.0" length="${arm_length}" radius="${arm_radius}">
            <origin xyz="${arm_length/2} 0 0" rpy="0 ${pi/2} 0"/>
        </xacro:inertial_cylinder>
    </link>

    <!-- CAMERA JOINT -->
    <joint name="camera_joint" type="fixed">
        <origin xyz="${arm_length} 0 ${arm_radius + 0.075}" rpy="0 0 0"/>
        <parent link="arm_link"/>
        <child link="camera_link"/>        
    </joint>

    <!-- CAMERA LINK -->
    <link name="camera_link">
        <visual>
            <origin xyz="-0.03 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0.06 0.15 0.15" />
            </geometry>
            <material name="white" />
        </visual>
        <visual>
            <origin xyz="0.03 0 0" rpy="0 ${pi/2} 0"/>
            <geometry>
                <cylinder length="0.06" radius="0.04" />
            </geometry>
            <material name="blue" />
        </visual>
        <collision>
            <origin xyz="0.0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0.12 0.15 0.15" />
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.1" x="0.12" y="0.15" z="0.15">
            <origin xyz="0.0 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

</robot>
